-- AlterTable
ALTER TABLE `orders` ADD COLUMN `notes` TEXT NULL,
    ADD COLUMN `paymentReceiptUrl` VARCHAR(191) NULL,
    MODIFY `status` ENUM('PENDING', 'PAID', 'CANCELLED', 'PENDING_RECEIPT', 'PAYMENT_REVIEW', 'PAYMENT_VERIFIED', 'PROCESSING', 'SHIPPED', 'DELIVERED') NOT NULL DEFAULT 'PENDING_RECEIPT';
